include:
  - ./BCovrin01/docker-compose.yml
  - ./BCovrin02/docker-compose.yml
  - ./BCovrin03/docker-compose.yml
  - ./BCovrin04/docker-compose.yml
  - ./LedgerMonitor/docker-compose.yml

networks:
  nodes:
    name: ${NODE_NETWORK}
    driver: bridge

  proxy:
    name: ${PROXY_NETWORK}
    external: true
